image: node:15.12-alpine3.13

stages:
 - test
 - deploy

test:
 stage: test
 script:
  - yarn install
  - yarn build
 except:
  - main

pages:
 stage: deploy
 script:
  - yarn install
  - yarn build
  - mv ./build ./public
 artifacts:
  paths:
   - public
 rules:
   - if: $CI_COMMIT_BRANCH == "main"
