image: node:15.12-alpine3.13

stages:
 - test
 - deploy

test:
 stage: test
 before_script:
   - yarn install
 script:
  - yarn build
 only:
   - main
 except:
  changes: 
    - README.md

pages:
 stage: deploy
 before_script:
   - yarn install
 script:
  - yarn build
  - mv ./build ./public
 artifacts:
  paths:
   - public
 only:
   - main
 except:
  changes: 
    - README.md
